apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    {{ toYaml .Values.spec.additionalMetadata | nindent 2}}
spec:
  destination:
    namespace:  kube-system
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    path: {{ .Values.spec.appsSharedPath }}gatekeeper-policies
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}

