apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-services
  labels:
    app: {{ template "prometheus.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  alertmanager.yaml: |-
      {{ .Files.Get "scData/alertmanager-sc-content.yaml" | b64enc | indent 12 }}
