apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: services
spec:
  externalUrl:  https://alertmanager
  replicas: 3
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-services
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9093
      protocol: TCP
      targetPort: web
  selector:
    alertmanager: services
