{{ if .Values.spec.monitoringSystem.grafanaReporter.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-reporter
  namespace: argo-cd
  annotations:
    recipients.argocd-notifications.argoproj.io: "{{.Values.spec.slackChannel}}"
  {{ toYaml .Values.spec.additionalMetadata | nindent 2}}
spec:
  destination:
    namespace: monitoring-system
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  {{- with .Values.spec.syncPolicy }}
  syncPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  source:
    path: {{ .Values.spec.appsMonitoring }}grafana-reporter
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      values: |
        image:
          repository: {{ .Values.spec.monitoringSystem.grafanaReporter.image.repository }}
          tag: {{ .Values.spec.monitoringSystem.grafanaReporter.image.tag }}
        grafana:
          endpoint: {{ .Values.spec.monitoringSystem.grafanaReporter.grafana.endpoint }}:{{ .Values.spec.monitoringSystem.grafanaReporter.grafana.port }}
        renderer:
          image:
            repository: {{ .Values.spec.monitoringSystem.grafanaReporter.renderer.image.repository }}
            tag: {{ .Values.spec.monitoringSystem.grafanaReporter.renderer.image.tag }}
      valueFiles:
        - values.yaml
{{- end }}
