{{ if .Values.spec.monitoringSystem.promethuesYace.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promethues-yace-preprod
  namespace: argo-cd
  annotations:
    recipients.argocd-notifications.argoproj.io: "{{.Values.spec.slackChannel}}"
  {{ toYaml .Values.spec.additionalMetadata | nindent 2}}
spec:
  destination:
    namespace: monitoring-system
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  {{- with .Values.spec.syncPolicy }}
  syncPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  source:
    path: {{ .Values.spec.appsMonitoring }}prometheus-yace-exporter
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - values.yaml
      values: |
        image:
          repository:  {{ .Values.spec.monitoringSystem.promethuesYace.image.repository }}
          tag:  {{ .Values.spec.monitoringSystem.promethuesYace.image.tag }}
        aws:
          aws_access_key_id: {{ .Values.spec.monitoringSystem.promethuesYace.aws.aws_access_key_id }}
          aws_secret_access_key: {{ .Values.spec.monitoringSystem.promethuesYace.aws.aws_secret_access_key }}
        serviceAccount:
          annotations:
            {{ range $key, $value := .Values.spec.monitoringSystem.promethuesYace.serviceAccount.annotations }}
            {{ $key }}: {{ $value }}
            {{- end }}
{{- end }}
